"""Core memory engine — the central coordinator for all memory operations.

All adapters (MCP, REST, direct Python) route through this class.
See docs/architecture.md for the full design.
"""

from __future__ import annotations

# Placeholder — implementation in WO-04
# Interface sketch for reference:

# class MemoryEngine:
#     def __init__(self, db: Database, config: Config) -> None: ...
#
#     # Session management
#     def start_session(self, agent_name: str | None = None, model_name: str | None = None) -> Session: ...
#     def end_session(self, session_id: str, note: str | None = None) -> Session: ...
#     def get_active_session(self) -> Session | None: ...
#
#     # Ingest
#     def ingest(self, events: list[EventInput]) -> list[Event]: ...
#     def ingest_one(self, type: EventType, content: str, metadata: dict | None = None) -> Event: ...
#
#     # Retrieval
#     def search(self, query: str, **kwargs) -> list[SearchResult]: ...
#     def get_briefing(self, max_tokens: int | None = None, focus: str | None = None) -> Briefing: ...
#
#     # Entities
#     def get_entities(self, type: str | None = None, status: str | None = None) -> list[Entity]: ...
#     def set_pinned(self, entity_id: str, pinned: bool) -> Entity: ...
