"""MCP tool definitions for llm-mem.

Each function here becomes an MCP tool that coding agents can invoke.
See docs/mcp-integration.md for the full tool specification.
"""

from __future__ import annotations

# Placeholder — implementation in WO-05
# Tool handler signatures for reference:

# async def handle_session_start(args: dict) -> dict: ...
# async def handle_ingest(args: dict) -> dict: ...
# async def handle_search(args: dict) -> dict: ...
# async def handle_get_briefing(args: dict) -> dict: ...
# async def handle_get_tasks(args: dict) -> dict: ...
# async def handle_pin(args: dict) -> dict: ...
# async def handle_update_task(args: dict) -> dict: ...
# async def handle_session_end(args: dict) -> dict: ...
